import { StyleSheet } from "react-native";

const BAR_HEIGHT = 64;

export default StyleSheet.create({
  container: {
    flex: 1,
    paddingHorizontal: 10,
    paddingTop: 10,
    paddingBottom: BAR_HEIGHT + 16,
  },
  header: { fontSize: 22, fontWeight: "600", marginVertical: 10 },
  preview: {
    alignItems: "center",
    borderRadius: 16,
    overflow: "hidden",
    backgroundColor: "#e4e4e471",
    padding: 8,
  },
  image: {
    width: "100%",
    height: undefined,
    aspectRatio: 3 / 4,
    maxHeight: 250,
    borderRadius: 12,
    marginTop: 12,
    alignSelf: "center",
  },
  bottomBar: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    height: BAR_HEIGHT,
    backgroundColor: "#fff",
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: "#e6e6e6",
    flexDirection: "row",
    justifyContent: "space-around",
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.06,
    shadowRadius: 6,
    elevation: 8,
  },
  tabItem: {
    width: 48,
    height: 48,
    alignItems: "center",
    justifyContent: "center",
  },
  cameraWrap: {
    position: "absolute",
    bottom: BAR_HEIGHT / 3,
    alignSelf: "center",
  },
  cameraButton: {
    width: 64,
    height: 64,
    borderRadius: 999,
    backgroundColor: "#000",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.2,
    shadowRadius: 12,
    elevation: 10,
  },
  modalContainer: {
    flex: 1,
    backgroundColor: "#000",
    justifyContent: "center",
    alignItems: "center",
  },
  closeButton: {
    position: "absolute",
    top: 48,
    right: 20,
    zIndex: 10,
    padding: 8,
  },
  modalImage: {
    flex: 1,
    alignSelf: "stretch",
  },
  zoomContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  nothing: {
    marginTop: 80,
    marginBottom: 80,
    alignItems: "center",
    height: 100,
    fontSize: 30,
    fontFamily: "CaveatBrushRegular",
  },
  calendarWrapper: {
    borderRadius: 16,
    padding: 10,
    overflow: "hidden",
    marginBottom: 10,
  },
  calendarCard: {
    borderRadius: 10,
    backgroundColor: "transparent",
  },
  pageWrap: {
    flexGrow: 1,
    alignItems: "center",
    justifyContent: "flex-start",
    padding: 16,
    gap: 12,
  },
  pageTitle: { fontSize: 22, fontWeight: "700" },
  pageSubtitle: { fontSize: 16, fontWeight: "600", marginTop: 8 },
  pageText: { fontSize: 15, color: "#444" },
  pageHint: { fontSize: 12, color: "#777", marginTop: 8 },
  colorRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
    marginTop: 12,
  },
  colorSwatch: {
    width: 44,
    height: 44,
    borderRadius: 12,
    borderWidth: 1,
    alignItems: "center",
    justifyContent: "center",
  },
  colorSwatchSelected: {
    borderWidth: 2,
    borderColor: "#111",
  },
  devBtn: {
    alignSelf: "flex-end",
    marginBottom: 8,
    marginRight: 4,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
    backgroundColor: "#f4f4f4",
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
});
